
name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main   # Trigger deployment on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy index.html to EC2
        run: |
          scp index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/index.html
          
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /tmp/index.html /var/www/html/index.html
            # Restart web server (detect nginx or apache)
            if systemctl list-units --type=service | grep -q nginx; then
              sudo systemctl restart nginx
            else
              sudo systemctl restart httpd
            fi
          EOF
